FROM scratch

LABEL org.opencontainers.image.title="Stash Bulk Transcode Plugin"
LABEL org.opencontainers.image.description="Image artifact containing the Stash bulk_transcode plugin files."

COPY plugins/bulk_transcode/README.md /plugins/bulk_transcode/README.md
COPY plugins/bulk_transcode/bulk_transcode.py /plugins/bulk_transcode/bulk_transcode.py
COPY plugins/bulk_transcode/bulk_transcode.yml /plugins/bulk_transcode/bulk_transcode.yml
COPY plugins/bulk_transcode/bulk_transcode_ui.css /plugins/bulk_transcode/bulk_transcode_ui.css
COPY plugins/bulk_transcode/bulk_transcode_ui.js /plugins/bulk_transcode/bulk_transcode_ui.js
