name: Compiler Build

on:
  workflow_dispatch:

env:
  COMPILER_IMAGE: ghcr.io/stashapp/compiler:13

jobs:
  build-compiler:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
    - uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        push: true
        context: "{{defaultContext}}:docker/compiler"
        tags: |
          ${{ env.COMPILER_IMAGE }}
          ghcr.io/stashapp/compiler:latest
        cache-from: type=gha,scope=all,mode=max
        cache-to: type=gha,scope=all,mode=max