name: package
on:
  push:
    tags:
      - v*
permissions:
  attestations: write
  contents: read
  id-token: write
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            GITHASH=${{ github.sha }}
            STASH_VERSION=${{ github.ref_name }}
          builder: ${{ steps.buildx.outputs.name }}
          file: ./docker/Dockerfile-CUDAJELLY
          platforms: linux/amd64,linux/arm64
          provenance: true
          push: true
          sbom: true
          tags: ghcr.io/${{ github.actor }}/stash:${{ github.ref_name }}
